server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL
    path(route='', view=views.get_dealerships, name='index'),
    path(route='about', view=views.about, name='about'),
    path(route='contact', view=views.contact, name='contact'),
    path('registration/', views.registration_request, name='registration'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path(route='dealer/<int:dealer_id>/', view=views.get_dealer_details, name='dealer_details'),
    path(route='dealer/<int:dealer_id>/review', view=views.add_review, name='add_review'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangoapp/models.py
from django.db import models
from django.utils.timezone import now
from django.core import serializers 
import uuid
import json

# Create your models here.

# <HINT> Create a Car Make model `class CarMake(models.Model)`:
# - Name
# - Description
# - Any other fields you would like to include in car make model
# - __str__ method to print a car make object
class CarMake(models.Model):
    name = models.CharField(null=False, max_length=20, default='undefined')
    description = models.TextField(null=True)
    def __str__(self):
        return self.name + ": " + self.description

# <HINT> Create a Car Model model `class CarModel(models.Model):`:
# - Many-To-One relationship to Car Make model (One Car Make has many Car Models, using ForeignKey field)
# - Name
# - Dealer id, used to refer a dealer created in cloudant database
# - Type (CharField with a choices argument to provide limited choices such as Sedan, SUV, WAGON, etc.)
# - Year (DateField)
# - Any other fields you would like to include in car model
# - __str__ method to print a car make object
class CarModel(models.Model):
    make = models.ForeignKey(CarMake, null=False, on_delete=models.CASCADE)  
    name = models.CharField(null=False, max_length=40, default='undefined')
    id = models.IntegerField(default=1,primary_key=True)        

    # One way -------------------
    # car_type = models.CharField(max_length=20, choices=[('Sedan', 'sedan'), ('SUV', 'suv'), ('WAGON', 'wagon')])

    # Another way -------------------
    type = models.CharField(
        null=False,
        max_length=20,
        choices=[('Sedan', 'sedan'), ('SUV', 'suv'), ('WAGON', 'wagon')],
        default='Sedan'
    )
    
    year = models.DateTimeField('date designed')
    def __str__(self):
        return self.type

# <HINT> Create a plain Python class `CarDealer` to hold dealer data
class CarDealer:
    def __init__(self, address, city, full_name, id, lat, long, st, zip):
        self.address = address
        self.city = city
        self.full_name=full_name
        self.id = id
        self.lat = lat
        self.long = long
        self.st = st
        self.zip = zip
    def __str__(self):
        return "Dealer name: " + self.full_name

# <HINT> Create a plain Python class `DealerReview` to hold review data
class DealerReview:
    def __init__(self, dealership, name, purchase, review):
        # Required attributes
        self.dealership = dealership
        self.name = name
        self.purchase = purchase
        self.review = review
        # Optional attributes
        self.purchase_date = ""
        self.purchase_make = ""
        self.purchase_model = ""
        self.purchase_year = ""
        self.sentiment = ""
        self.id = ""
    def __str__(self):
        return "Review: " + self.review
    def to_json(self):
        return json.dumps(self, default=lambda o: o.__dict__,
                            sort_keys=True, indent=4)

class ReviewPost:
    def __init__(self, dealership, name, purchase, review):
        # Required attributes
        self.dealership = dealership
        self.name = name
        self.purchase = purchase
        self.review = review
        # Optional attributes
        self.purchase_date = ""
        self.car_make = ""
        self.car_model = ""
        self.car_year = ""
    def to_json(self):
        return json.dumps(self, default=lambda o: o.__dict__,
                            sort_keys=True, indent=4)

server/djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from .models import CarModel, CarMake, CarDealer, DealerReview, ReviewPost
from .restapis import get_dealers_from_cf, get_dealer_by_id_from_cf, get_dealer_reviews_from_cf, post_request
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
import logging
import json

# Get an instance of a logger
logger = logging.getLogger(__name__)

# Create your views here.

# Create an `about` view to render a static about page
def about(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/about.html', context)

# Create a `contact` view to return a static contact page
def contact(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/contact.html', context)

# Create a `login_request` view to handle sign in request
def login_request(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('djangoapp:index')
        else:
            context['message'] = "Invalid username or password."
            return render(request, 'djangoapp/login.html', context)
    else:
        return render(request, 'djangoapp/login.html', context)

# Create a `logout_request` view to handle sign out request
def logout_request(request):
    print("Logging out `{}`...".format(request.user.username))
    logout(request)
    return redirect('djangoapp:index')

# Create a `registration_request` view to handle sign up request
def registration_request(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/registration.html', context)
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.debug("{} is new user".format(username))
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            login(request, user)
            return redirect("/djangoapp/")
        else:
            return render(request, 'djangoapp/registration.html', context)

# Update the `get_dealerships` view to render the index page with a list of dealerships
def get_dealerships(request):
    if request.method == "GET":
        context = {}
        url = "https://d6f5d202.us-south.apigw.appdomain.cloud/api1/dealership"

        dealerships = get_dealers_from_cf(url)
        context["dealership_list"] = dealerships
        return render(request, 'djangoapp/index.html', context)
    
# Create a `get_dealer_details` view to render the reviews of a dealer
# def get_dealer_details(request, dealer_id):
# ...
def get_dealer_details(request, id):
    dealer_url     = "https://d6f5d202.us-south.apigw.appdomain.cloud/api1/dealership"
    postreview_url = "https://d6f5d202.us-south.apigw.appdomain.cloud/api/postreview"
    getreview_url  = "https://d6f5d202.us-south.apigw.appdomain.cloud/api2/getreview"
    if request.method == "GET":
        context = {}
        dealer = get_dealer_by_id_from_cf(dealer_url, id=id)
        context["dealer"] = dealer
        reviews = get_dealer_reviews_from_cf(getreview_url, id=id)
        print(reviews)
        context["reviews"] = reviews
        return render(request, 'djangoapp/dealer_details.html', context)

# Create a `add_review` view to submit a review
# def add_review(request, dealer_id):
def add_review(request, id):
    dealer_url      = "https://d6f5d202.us-south.apigw.appdomain.cloud/api1/dealership"
    postreview_url  = "https://d6f5d202.us-south.apigw.appdomain.cloud/api/postreview"
    getreview_url   = "https://d6f5d202.us-south.apigw.appdomain.cloud/api2/getreview"
    context = {}
    dealer = get_dealer_by_id_from_cf(dealer_url, id=id)
    context["dealer"] = dealer
    if request.method == 'GET':
        cars = CarModel.objects.all()
        print(cars)
        context["cars"] = cars
        return render(request, 'djangoapp/add_review.html', context)
    elif request.method == 'POST':
        if request.user.is_authenticated:
            username = request.user.username
            print(request.POST)
            payload = dict()
            car_id = request.POST["car"]
            car = CarModel.objects.get(pk=car_id)
            payload["time"] = datetime.utcnow().isoformat()
            payload["name"] = username
            payload["dealership"] = id
            payload["id"] = id
            payload["review"] = request.POST["content"]
            payload["purchase"] = False
            if "purchasecheck" in request.POST:
                if request.POST["purchasecheck"] == 'on':
                    payload["purchase"] = True
            payload["purchase_date"] = request.POST["purchasedate"]
            payload["car_make"] = car.make.name
            payload["car_model"] = car.name
            payload["car_year"] = int(car.year.strftime("%Y"))
            new_payload = {}
            new_payload["review"] = payload
            post_request(postreview_url, new_payload, id=id)
        return redirect("djangoapp:dealer_details", id=id)

server/djangoapp/templates/djangoapp/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

</head>

    <body>
    <!-- Remove this line the first time you edit this file -->

    <!--Add a nav bar here -->

    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Dealership Review</a>
            </div>
            <ul class="nav navbar navbar-right">
                <li class="pr-5">
                    <a class="text-dark" href="{% url 'djangoapp:index' %}">Home</a>
                </li>
                <li class="pr-5">
                    <a class="text-dark" href="{% url 'djangoapp:about' %}">About Us</a>
                </li>
                <li class="pr-5">
                    <a class="text-dark" href="{% url 'djangoapp:contact' %}">Contact Us</a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'djangoapp:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Password" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
        <h1>
            Welcome to Best Cars dealership, home to the best cars in North America. We sell domestic and imported cars at reasonable prices.
        </h1>

    </body>

</html>

server/djangoapp/templates/djangoapp/add_review.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

</head>

<body>
    <!--Add a nav bar here -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'djangoapp:index' %}"><b>Dealership Review</b></a>
                <a class="navbar-brand" href="{% url 'djangoapp:about' %}">About Us</a>
                <a class="navbar-brand" href="{% url 'djangoapp:contact' %}">Contact Us</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'djangoapp:login' %}" method="POST">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username">
                            <input type="password" class="form-control" placeholder="Password" name="psw">
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

      <!--Add a dealer review here -->
    <main class="container">
        <h4>Add a review for {{dealer.full_name}}</h4>
        <br>
        <form action="{% url 'djangoapp:add_review' dealer.id%}" method="post">    
            {% csrf_token %}
            <div class="form-group">
                <label for="content"><b>Enter review content:</b></label>
                <textarea class="form-control" id="content" name="content" rows="2" required></textarea>
            </div>
            <div class="form-group form-check">
                <input class="form-check-input" type="checkbox" name="purchasecheck" id="purchasecheck">
                <label for="purchasecheck">Did you purchase the car? </label>
            </div>
            <div class="form-group">
                <label for="car"><b>Select your car (model-make-year):</b></label>
                <select name="car" id="car" class="form-select" required>
                    {% for car in cars %}
                        <option selected value={{car.id}}>{{car.car_make.name}} {{car.name}} {{ car.year }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group" data-provide="datepicker">
                <label for="purchasedate">Select your purchase date (mm/dd/yyyy):</label>
                <input class="date-own form-control" type="text" name="purchasedate" id="purchasedate">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </main>
</body>

<script type="text/javascript">
    $('.date-own').datepicker({
       format: 'mm/dd/yyyy'
     });
</script>

</html>

server/djangoapp/templates/djangoapp/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

</head>

    <body>
    <!-- Remove this line the first time you edit this file -->

    <!--Add a nav bar here -->

    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Dealership Review</a>
            </div>
            <ul class="nav navbar navbar-right">
                <li class="pr-5">
                    <a class="text-dark" href="{% url 'djangoapp:index' %}">Home</a>
                </li>
                <li class="pr-5">
                    <a class="text-dark" href="{% url 'djangoapp:about' %}">About Us</a>
                </li>
                <li class="pr-5">
                    <a class="text-dark" href="{% url 'djangoapp:contact' %}">Contact Us</a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'djangoapp:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Password" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <center>
        <h1>
            Address
        </h1>
        <p>
            Earth
        </p>
        <h1>
            Phone No
        </h1>
        <p>
            12345678
        </p>
    </center>


    </body>

</html>

server/djangoapp/templates/djangoapp/dealer_details.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
</head>

<body>
    <!--Add a nav bar here -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'djangoapp:index' %}"><b>Dealership Review</b></a>
                <a class="navbar-brand" href="{% url 'djangoapp:about' %}">About Us</a>
                <a class="navbar-brand" href="{% url 'djangoapp:contact' %}">Contact Us</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'djangoapp:login' %}" method="POST">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username">
                            <input type="password" class="form-control" placeholder="Password" name="psw">
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!--Add a dealer table here -->
    {% if reviews %}
        {% if user.is_authenticated %}
            <div style="margin: 10px;">
                <a class="btn btn-primary" href="{% url 'djangoapp:add_review' dealer.id %}"><b>Write a car review</b></a>
            </div>
        {% endif %}
        <div class="card-columns">
            {% for review in reviews %}
                {% if review.car_make %}
                <div class="card" style="height: 300px; overflow: scroll; overflow-x: hidden;">
                    <img src="{{MEDIA_URL}}/emoji/{{review.sentiment}}.png" class="card-img-left" style="float: left; height: 40px; width: 40px; display: inline-block;">
                    <div class="card-body" style="text-align: center;">
                        <h5 class="card-title" style="display: inline-block;">{{ review.car_make }}, {{ review.car_model }}</h5>
                        <h5 class="card-title">{{ review.car_year }}</h5>
                        <p class="card-text" style="text-align: left;">{{ review.review }}</p>
                    </div>
                </div>
                <!-- some review data may be missing , using default values-->
                {% else %}
                <div class="card" style="height: 300px; overflow: scroll; overflow-x: hidden;">
                    <img src="{{MEDIA_URL}}/emoji/{{review.sentiment}}.png" class="card-img-left" style="float: left; height: 40px; width: 40px; display: inline-block;">
                    <div class="card-body" style="text-align: center;">
                        <h5 class="card-title" style="display: inline-block;">Review</h5>
                        <h5 class="card-title"></h5>
                        <p class="card-text" style="text-align: left;">{{ review.review }}</p>
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        </div>
    {% else %}
        <p></br>There are no reviews for this dealership.</br></p>
        {% if user.is_authenticated %}
            <div style="margin: 10px;">
                <a class="btn btn-primary" href="{% url 'djangoapp:add_review' dealer.id %}"><b>Write a car review</b></a>
            </div>
        {% endif %}
    {% endif %}

</body>
</html>

server/djangoapp/templates/djangoapp/index.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

</head>

<body>
    <!--Add a nav bar here -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'djangoapp:index' %}"><b>Dealership Review</b></a>
                <a class="navbar-brand" href="{% url 'djangoapp:about' %}">About Us</a>
                <a class="navbar-brand" href="{% url 'djangoapp:contact' %}">Contact Us</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'djangoapp:login' %}" method="POST">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username">
                            <input type="password" class="form-control" placeholder="Password" name="psw">
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

      <!--Add a dealer table here -->
      <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <table class="table" id="table"
            data-filter-control="true">
            <thead>
                <tr>
                    <th data-field="id">ID</th>
                    <th data-field="full_name">Dealer Name</th>
                    <th data-field="city">City</th>
                    <th data-field="address">Address</th>
                    <th data-field="zip">Zip</th>
                    <th data-field="state" data-filter-control="select">State</th>
                </tr>
            </thead>
            <tbody>
                {% for dealer in dealership_list %}
                    <tr>
                        <td>{{dealer.id}}</td>
                        <td><a href="{% url 'djangoapp:dealer_details' dealer.id %}">{{dealer.full_name}}</a></td>
                        <td>{{dealer.city}}</td>
                        <td>{{dealer.address}}</td>
                        <td>{{dealer.zip}}</td>
                        <td>{{dealer.st}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
</body>

    <script>
    $(function() {
        $('#table').bootstrapTable()
    })
    </script>

</html>

server/djangoapp/templates/djangoapp/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
    <body>
      <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'djangoapp:index' %}">Dealership Review</a>
                <a class="navbar-brand" href="{% url 'djangoapp:about' %}">About Us</a>
                <a class="navbar-brand" href="{% url 'djangoapp:contact' %}">Contact Us</a>
            </div>
        </div>
    </nav>
    <!--Add a registration form here -->
    <form action="{% url 'djangoapp:registration' %}" method="POST">
        <div class="container lead mt-5 text-left">
            <h1>Sign Up</h1>
            <hr>
            <div class="card-columns-vertical">
                <label for="username"><b>User Name</b></label>
                <input type="text" class="form-control" placeholder="Username" name="username" required>
                <label for="firstname"><b>First Name</b></label>
                <input type="text" class="form-control" placeholder="Firstname" name="firstname" required>
                <label for="lastname"><b>Last Name</b></label>
                <input type="text" class="form-control" placeholder="Lastname" name="lastname" required>
                <label for="psw"><b>Password</b></label>
                <input type="password" class="form-control" placeholder="Password" name="psw" required>
            </div>
            <div>
                {% csrf_token %}
                <button class="btn btn-primary mt-3" type="submit">Sign Up</button>
            </div>
        </div>
    </form>
    </body>
</html>